defaults:
  - _self_

run_cfg:
  dataset_id: WISDM_19_PHONE
  epochs: 50
  patience: 5
  batch_size: 128
  learning_rate: 0.001
  tracker_backend: wandb # mlflow
  tracking_uri: http://localhost:5001

data:
  base_dir: datasets
  sensor_channels: null
  parallelize: true
